version: "2"
services:
  node:
    build:
      context: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./src/:/home/node/app
    expose:
      - "8081"
    command: "npm start"